// app.js

// Define el token corto
const TOKEN = "26D-VeRuyhR7q6sP_PoXXQgQ24AeyJhbW91bnQiOjQ1MDAsImN1cnJlbmN5IjoiUEVOIiwibW9kZSI6IlRFU1QiLCJ2ZXJzaW9uIjozLCJvcmRlcklkIjoiMTM2Iiwic2hvcE5hbWUiOiJDTElOSUNBIElOVEVSTkFDSU9OQUwgU1VQRVIgQVBQIChCT1RPTiBBUFAgU09MRVMpICg0MDc5NzUyKSIsImZvcm1BY3Rpb24iOiJQQVlNRU5UIiwicmlza0FuYWx5c2VyIjp7ImZpbmdlclByaW50c0lkIjoiMDA5NGVkYTMtNDg1YS00MzUwLWE2MDYtMmIwNWYyNzVjOTVjIiwianNVcmwiOiJodHRwczovL3NlY3VyZS5taWN1ZW50YXdlYi5wZS90cmFzL2FuYWx5emVyL3B1YmxpYy92MS9jaGVja2VyLzAwOTRlZGEzLTQ4NWEtNDM1MC1hNjA2LTJiMDVmMjc1Yzk1YyJ9LCJjYXRlZ29yaWVzIjp7ImRlYml0Q3JlZGl0Q2FyZHMiOnsiYXBwSWQiOiJjYXJkcyIsInBhcmFtIjpbIkFNRVgiLCJNQVNURVJDQVJEX0RFQklUIiwiTUFTVEVSQ0FSRCIsIlZJU0EiLCJWSVNBX0VMRUNUUk9OIiwiVklTQV9ERUJJVCIsIkRJTkVSUyJdfX0sImNhcmRzIjp7IkFNRVgiOnsiZmllbGRzIjp7InNlY3VyaXR5Q29kZSI6eyJtYXhMZW5ndGgiOjR9fSwiY29weUZyb20iOiJjYXJkcy5ERUZBVUxUIn0sIk1BU1RFUkNBUkRfREVCSVQiOnsiY29weUZyb20iOiJjYXJkcy5ERUZBVUxUIn0sIk1BU1RFUkNBUkQiOnsiY29weUZyb20iOiJjYXJkcy5ERUZBVUxUIn0sIlZJU0EiOnsiY29weUZyb20iOiJjYXJkcy5ERUZBVUxUIn0sIlZJU0FfRUxFQ1RST04iOnsiY29weUZyb20iOiJjYXJkcy5ERUZBVUxUIn0sIkRFRkFVTFQiOnsiZmllbGRzIjp7InBhbiI6eyJtaW5MZW5ndGgiOjEwLCJtYXhMZW5ndGgiOjE5LCJ2YWxpZGF0b3JzIjpbIk5VTUVSSUMiLCJMVUhOIl0sInJlcXVpcmVkIjp0cnVlLCJzZW5zaXRpdmUiOnRydWUsImhpZGRlbiI6ZmFsc2UsImNsZWFyT25FcnJvciI6dHJ1ZX0sImV4cGlyeURhdGUiOnsicmVxdWlyZWQiOnRydWUsInNlbnNpdGl2ZSI6dHJ1ZSwiaGlkZGVuIjpmYWxzZSwiY2xlYXJPbkVycm9yIjp0cnVlfSwic2VjdXJpdHlDb2RlIjp7Im1pbkxlbmd0aCI6MywibWF4TGVuZ3RoIjozLCJ2YWxpZGF0b3JzIjpbIk5VTUVSSUMiXSwicmVxdWlyZWQiOnRydWUsInNlbnNpdGl2ZSI6dHJ1ZSwiaGlkZGVuIjpmYWxzZSwiY2xlYXJPbkVycm9yIjp0cnVlfX19LCJWSVNBX0RFQklUIjp7ImNvcHlGcm9tIjoiY2FyZHMuREVGQVVMVCJ9LCJESU5FUlMiOnsiY29weUZyb20iOiJjYXJkcy5ERUZBVUxUIn19LCJhcGlSZXN0VmVyc2lvbiI6IjQuMCIsImNvdW50cnkiOiJQRSIsImpTZXNzaW9uSWQiOiJjZTc3OEZlNDJjYWFhY0NDY2REMkUyM0UyRDgxYkVDN2JDZkQ5NjZBLnZhZHdvcmxkYXBpMDItdGxzLXByb2QtZnItbHlyYSJ95902"; // Token de ejemplo corto

// Asigna dinámicamente el token al formulario
document.addEventListener("DOMContentLoaded", function () {
  const paymentForm = document.getElementById("payment-form");
  paymentForm.setAttribute("kr-form-token", TOKEN);

  // Configura los eventos de éxito y error en el pago como funciones globales
  window.onPaymentSuccess = onPaymentSuccess;
  window.onPaymentError = onPaymentError;
});

// Función que se ejecuta cuando el pago se realiza con éxito
function onPaymentSuccess(event) {
  console.log('Pago realizado con éxito:', event);
  alert("Pago realizado con éxito!");
}

// Función que se ejecuta cuando hay un error en el pago
function onPaymentError(event) {
  console.error('Error en el pago:', event);
  alert("Error en el pago. Por favor, intente nuevamente.");
}
